/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudentLifeRouteImport } from './routes/student-life'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as OurModelRouteImport } from './routes/our-model'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LearningJourneyRouteImport } from './routes/learning-journey'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CampusesRouteImport } from './routes/campuses'
import { Route as CampusExperienceRouteImport } from './routes/campus-experience'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AcademicExperienceRouteImport } from './routes/academic-experience'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentLifeWellbeingRouteImport } from './routes/student-life_.wellbeing'
import { Route as StudentLifeLeadershipServiceRouteImport } from './routes/student-life_.leadership-service'
import { Route as StudentLifeEventsRouteImport } from './routes/student-life_.events'
import { Route as StudentLifeCommunityBelongingRouteImport } from './routes/student-life_.community-belonging'
import { Route as StudentLifeClubsActivitiesRouteImport } from './routes/student-life_.clubs-activities'
import { Route as StudentLifeAthleticsRouteImport } from './routes/student-life_.athletics'
import { Route as StudentLifeArtsPerformanceRouteImport } from './routes/student-life_.arts-performance'
import { Route as ParentsSchoolPoliciesRouteImport } from './routes/parents_.school-policies'
import { Route as ParentsSchoolCalendarRouteImport } from './routes/parents_.school-calendar'
import { Route as ParentsParentPortalRouteImport } from './routes/parents_.parent-portal'
import { Route as ParentsParentPartnershipRouteImport } from './routes/parents_.parent-partnership'
import { Route as ParentsParentJourneyRouteImport } from './routes/parents_.parent-journey'
import { Route as ParentsFamilyResourcesRouteImport } from './routes/parents_.family-resources'
import { Route as ParentsFamilyEngagementRouteImport } from './routes/parents_.family-engagement'
import { Route as ParentsCommunicationRouteImport } from './routes/parents_.communication'
import { Route as OurModelTeachingFrameworkRouteImport } from './routes/our-model_.teaching-framework'
import { Route as OurModelStudentDevelopmentRouteImport } from './routes/our-model_.student-development'
import { Route as OurModelParentPartnershipRouteImport } from './routes/our-model_.parent-partnership'
import { Route as OurModelLearningEcosystemRouteImport } from './routes/our-model_.learning-ecosystem'
import { Route as OurModelLearnerProfileRouteImport } from './routes/our-model_.learner-profile'
import { Route as OurModelInstitutionalIntelligenceRouteImport } from './routes/our-model_.institutional-intelligence'
import { Route as OurModelInnovationRouteImport } from './routes/our-model_.innovation'
import { Route as OurModelGraduateProfileRouteImport } from './routes/our-model_.graduate-profile'
import { Route as OurModelEducationalModelRouteImport } from './routes/our-model_.educational-model'
import { Route as OurModelAssessmentFrameworkRouteImport } from './routes/our-model_.assessment-framework'
import { Route as NewsTeacherStoriesRouteImport } from './routes/news_.teacher-stories'
import { Route as NewsStudentStoriesRouteImport } from './routes/news_.student-stories'
import { Route as NewsSchoolNewsRouteImport } from './routes/news_.school-news'
import { Route as NewsResearchReflectionRouteImport } from './routes/news_.research-reflection'
import { Route as NewsParentGuidesRouteImport } from './routes/news_.parent-guides'
import { Route as NewsEducationalInsightsRouteImport } from './routes/news_.educational-insights'
import { Route as NewsCommunityStoriesRouteImport } from './routes/news_.community-stories'
import { Route as NewsCampusEventsRouteImport } from './routes/news_.campus-events'
import { Route as LearningJourneySecondaryRouteImport } from './routes/learning-journey_.secondary'
import { Route as LearningJourneyPrimaryRouteImport } from './routes/learning-journey_.primary'
import { Route as LearningJourneyPreparatoryRouteImport } from './routes/learning-journey_.preparatory'
import { Route as LearningJourneyGraduationPathwaysRouteImport } from './routes/learning-journey_.graduation-pathways'
import { Route as LearningJourneyEarlyYearsRouteImport } from './routes/learning-journey_.early-years'
import { Route as ExploreDigitalEcosystemRouteImport } from './routes/explore.digital-ecosystem'
import { Route as CommunityPartnershipsRouteImport } from './routes/community_.partnerships'
import { Route as CommunityEventsRouteImport } from './routes/community_.events'
import { Route as CommunityCommunityProgrammesRouteImport } from './routes/community_.community-programmes'
import { Route as CommunityCareersRouteImport } from './routes/community_.careers'
import { Route as CommunityAlumniRouteImport } from './routes/community_.alumni'
import { Route as CampusesMohandessinRouteImport } from './routes/campuses_.mohandessin'
import { Route as CampusExperienceTransportationRouteImport } from './routes/campus-experience_.transportation'
import { Route as CampusExperienceSportsFacilitiesRouteImport } from './routes/campus-experience_.sports-facilities'
import { Route as CampusExperienceSafetyRouteImport } from './routes/campus-experience_.safety'
import { Route as CampusExperienceOverviewRouteImport } from './routes/campus-experience_.overview'
import { Route as CampusExperienceOutdoorLearningRouteImport } from './routes/campus-experience_.outdoor-learning'
import { Route as CampusExperienceLibraryRouteImport } from './routes/campus-experience_.library'
import { Route as CampusExperienceLaboratoriesRouteImport } from './routes/campus-experience_.laboratories'
import { Route as CampusExperienceInnovationCreativeSpacesRouteImport } from './routes/campus-experience_.innovation-creative-spaces'
import { Route as CampusExperienceHealthServicesRouteImport } from './routes/campus-experience_.health-services'
import { Route as CampusExperienceDiningRouteImport } from './routes/campus-experience_.dining'
import { Route as CampusExperienceClassroomsRouteImport } from './routes/campus-experience_.classrooms'
import { Route as CampusExperienceAssemblyHallRouteImport } from './routes/campus-experience_.assembly-hall'
import { Route as AdmissionsTuitionFeesRouteImport } from './routes/admissions_.tuition-fees'
import { Route as AdmissionsScholarshipsRouteImport } from './routes/admissions_.scholarships'
import { Route as AdmissionsScheduleAVisitRouteImport } from './routes/admissions_.schedule-a-visit'
import { Route as AdmissionsRequirementsRouteImport } from './routes/admissions_.requirements'
import { Route as AdmissionsFaqRouteImport } from './routes/admissions_.faq'
import { Route as AdmissionsApplyOnlineRouteImport } from './routes/admissions_.apply-online'
import { Route as AdmissionsApplicationProcessRouteImport } from './routes/admissions_.application-process'
import { Route as AboutWhyLighthouseRouteImport } from './routes/about_.why-lighthouse'
import { Route as AboutVisionRouteImport } from './routes/about_.vision'
import { Route as AboutOurStoryRouteImport } from './routes/about_.our-story'
import { Route as AboutMissionRouteImport } from './routes/about_.mission'
import { Route as AboutLeadershipRouteImport } from './routes/about_.leadership'
import { Route as AboutGovernanceRouteImport } from './routes/about_.governance'
import { Route as AboutEducationalPhilosophyRouteImport } from './routes/about_.educational-philosophy'
import { Route as AboutCoreValuesRouteImport } from './routes/about_.core-values'
import { Route as AboutCampusCultureRouteImport } from './routes/about_.campus-culture'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeRoute = StudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const OurModelRoute = OurModelRouteImport.update({
  id: '/our-model',
  path: '/our-model',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningJourneyRoute = LearningJourneyRouteImport.update({
  id: '/learning-journey',
  path: '/learning-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesRoute = CampusesRouteImport.update({
  id: '/campuses',
  path: '/campuses',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusExperienceRoute = CampusExperienceRouteImport.update({
  id: '/campus-experience',
  path: '/campus-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicExperienceRoute = AcademicExperienceRouteImport.update({
  id: '/academic-experience',
  path: '/academic-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeWellbeingRoute = StudentLifeWellbeingRouteImport.update({
  id: '/student-life_/wellbeing',
  path: '/student-life/wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeLeadershipServiceRoute =
  StudentLifeLeadershipServiceRouteImport.update({
    id: '/student-life_/leadership-service',
    path: '/student-life/leadership-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentLifeEventsRoute = StudentLifeEventsRouteImport.update({
  id: '/student-life_/events',
  path: '/student-life/events',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeCommunityBelongingRoute =
  StudentLifeCommunityBelongingRouteImport.update({
    id: '/student-life_/community-belonging',
    path: '/student-life/community-belonging',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentLifeClubsActivitiesRoute =
  StudentLifeClubsActivitiesRouteImport.update({
    id: '/student-life_/clubs-activities',
    path: '/student-life/clubs-activities',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentLifeAthleticsRoute = StudentLifeAthleticsRouteImport.update({
  id: '/student-life_/athletics',
  path: '/student-life/athletics',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeArtsPerformanceRoute =
  StudentLifeArtsPerformanceRouteImport.update({
    id: '/student-life_/arts-performance',
    path: '/student-life/arts-performance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParentsSchoolPoliciesRoute = ParentsSchoolPoliciesRouteImport.update({
  id: '/parents_/school-policies',
  path: '/parents/school-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsSchoolCalendarRoute = ParentsSchoolCalendarRouteImport.update({
  id: '/parents_/school-calendar',
  path: '/parents/school-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsParentPortalRoute = ParentsParentPortalRouteImport.update({
  id: '/parents_/parent-portal',
  path: '/parents/parent-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsParentPartnershipRoute =
  ParentsParentPartnershipRouteImport.update({
    id: '/parents_/parent-partnership',
    path: '/parents/parent-partnership',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParentsParentJourneyRoute = ParentsParentJourneyRouteImport.update({
  id: '/parents_/parent-journey',
  path: '/parents/parent-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsFamilyResourcesRoute = ParentsFamilyResourcesRouteImport.update({
  id: '/parents_/family-resources',
  path: '/parents/family-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsFamilyEngagementRoute = ParentsFamilyEngagementRouteImport.update({
  id: '/parents_/family-engagement',
  path: '/parents/family-engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsCommunicationRoute = ParentsCommunicationRouteImport.update({
  id: '/parents_/communication',
  path: '/parents/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const OurModelTeachingFrameworkRoute =
  OurModelTeachingFrameworkRouteImport.update({
    id: '/our-model_/teaching-framework',
    path: '/our-model/teaching-framework',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurModelStudentDevelopmentRoute =
  OurModelStudentDevelopmentRouteImport.update({
    id: '/our-model_/student-development',
    path: '/our-model/student-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurModelParentPartnershipRoute =
  OurModelParentPartnershipRouteImport.update({
    id: '/our-model_/parent-partnership',
    path: '/our-model/parent-partnership',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurModelLearningEcosystemRoute =
  OurModelLearningEcosystemRouteImport.update({
    id: '/our-model_/learning-ecosystem',
    path: '/our-model/learning-ecosystem',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurModelLearnerProfileRoute = OurModelLearnerProfileRouteImport.update({
  id: '/our-model_/learner-profile',
  path: '/our-model/learner-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OurModelInstitutionalIntelligenceRoute =
  OurModelInstitutionalIntelligenceRouteImport.update({
    id: '/our-model_/institutional-intelligence',
    path: '/our-model/institutional-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurModelInnovationRoute = OurModelInnovationRouteImport.update({
  id: '/our-model_/innovation',
  path: '/our-model/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const OurModelGraduateProfileRoute = OurModelGraduateProfileRouteImport.update({
  id: '/our-model_/graduate-profile',
  path: '/our-model/graduate-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OurModelEducationalModelRoute =
  OurModelEducationalModelRouteImport.update({
    id: '/our-model_/educational-model',
    path: '/our-model/educational-model',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurModelAssessmentFrameworkRoute =
  OurModelAssessmentFrameworkRouteImport.update({
    id: '/our-model_/assessment-framework',
    path: '/our-model/assessment-framework',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsTeacherStoriesRoute = NewsTeacherStoriesRouteImport.update({
  id: '/news_/teacher-stories',
  path: '/news/teacher-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsStudentStoriesRoute = NewsStudentStoriesRouteImport.update({
  id: '/news_/student-stories',
  path: '/news/student-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSchoolNewsRoute = NewsSchoolNewsRouteImport.update({
  id: '/news_/school-news',
  path: '/news/school-news',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsResearchReflectionRoute = NewsResearchReflectionRouteImport.update({
  id: '/news_/research-reflection',
  path: '/news/research-reflection',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsParentGuidesRoute = NewsParentGuidesRouteImport.update({
  id: '/news_/parent-guides',
  path: '/news/parent-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsEducationalInsightsRoute = NewsEducationalInsightsRouteImport.update({
  id: '/news_/educational-insights',
  path: '/news/educational-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsCommunityStoriesRoute = NewsCommunityStoriesRouteImport.update({
  id: '/news_/community-stories',
  path: '/news/community-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsCampusEventsRoute = NewsCampusEventsRouteImport.update({
  id: '/news_/campus-events',
  path: '/news/campus-events',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningJourneySecondaryRoute =
  LearningJourneySecondaryRouteImport.update({
    id: '/learning-journey_/secondary',
    path: '/learning-journey/secondary',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearningJourneyPrimaryRoute = LearningJourneyPrimaryRouteImport.update({
  id: '/learning-journey_/primary',
  path: '/learning-journey/primary',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningJourneyPreparatoryRoute =
  LearningJourneyPreparatoryRouteImport.update({
    id: '/learning-journey_/preparatory',
    path: '/learning-journey/preparatory',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearningJourneyGraduationPathwaysRoute =
  LearningJourneyGraduationPathwaysRouteImport.update({
    id: '/learning-journey_/graduation-pathways',
    path: '/learning-journey/graduation-pathways',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearningJourneyEarlyYearsRoute =
  LearningJourneyEarlyYearsRouteImport.update({
    id: '/learning-journey_/early-years',
    path: '/learning-journey/early-years',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExploreDigitalEcosystemRoute = ExploreDigitalEcosystemRouteImport.update({
  id: '/explore/digital-ecosystem',
  path: '/explore/digital-ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPartnershipsRoute = CommunityPartnershipsRouteImport.update({
  id: '/community_/partnerships',
  path: '/community/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsRoute = CommunityEventsRouteImport.update({
  id: '/community_/events',
  path: '/community/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCommunityProgrammesRoute =
  CommunityCommunityProgrammesRouteImport.update({
    id: '/community_/community-programmes',
    path: '/community/community-programmes',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunityCareersRoute = CommunityCareersRouteImport.update({
  id: '/community_/careers',
  path: '/community/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAlumniRoute = CommunityAlumniRouteImport.update({
  id: '/community_/alumni',
  path: '/community/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesMohandessinRoute = CampusesMohandessinRouteImport.update({
  id: '/campuses_/mohandessin',
  path: '/campuses/mohandessin',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusExperienceTransportationRoute =
  CampusExperienceTransportationRouteImport.update({
    id: '/campus-experience_/transportation',
    path: '/campus-experience/transportation',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampusExperienceSportsFacilitiesRoute =
  CampusExperienceSportsFacilitiesRouteImport.update({
    id: '/campus-experience_/sports-facilities',
    path: '/campus-experience/sports-facilities',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampusExperienceSafetyRoute = CampusExperienceSafetyRouteImport.update({
  id: '/campus-experience_/safety',
  path: '/campus-experience/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusExperienceOverviewRoute =
  CampusExperienceOverviewRouteImport.update({
    id: '/campus-experience_/overview',
    path: '/campus-experience/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampusExperienceOutdoorLearningRoute =
  CampusExperienceOutdoorLearningRouteImport.update({
    id: '/campus-experience_/outdoor-learning',
    path: '/campus-experience/outdoor-learning',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampusExperienceLibraryRoute = CampusExperienceLibraryRouteImport.update({
  id: '/campus-experience_/library',
  path: '/campus-experience/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusExperienceLaboratoriesRoute =
  CampusExperienceLaboratoriesRouteImport.update({
    id: '/campus-experience_/laboratories',
    path: '/campus-experience/laboratories',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampusExperienceInnovationCreativeSpacesRoute =
  CampusExperienceInnovationCreativeSpacesRouteImport.update({
    id: '/campus-experience_/innovation-creative-spaces',
    path: '/campus-experience/innovation-creative-spaces',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampusExperienceHealthServicesRoute =
  CampusExperienceHealthServicesRouteImport.update({
    id: '/campus-experience_/health-services',
    path: '/campus-experience/health-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampusExperienceDiningRoute = CampusExperienceDiningRouteImport.update({
  id: '/campus-experience_/dining',
  path: '/campus-experience/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusExperienceClassroomsRoute =
  CampusExperienceClassroomsRouteImport.update({
    id: '/campus-experience_/classrooms',
    path: '/campus-experience/classrooms',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampusExperienceAssemblyHallRoute =
  CampusExperienceAssemblyHallRouteImport.update({
    id: '/campus-experience_/assembly-hall',
    path: '/campus-experience/assembly-hall',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsTuitionFeesRoute = AdmissionsTuitionFeesRouteImport.update({
  id: '/admissions_/tuition-fees',
  path: '/admissions/tuition-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsScholarshipsRoute = AdmissionsScholarshipsRouteImport.update({
  id: '/admissions_/scholarships',
  path: '/admissions/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsScheduleAVisitRoute =
  AdmissionsScheduleAVisitRouteImport.update({
    id: '/admissions_/schedule-a-visit',
    path: '/admissions/schedule-a-visit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsRequirementsRoute = AdmissionsRequirementsRouteImport.update({
  id: '/admissions_/requirements',
  path: '/admissions/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsFaqRoute = AdmissionsFaqRouteImport.update({
  id: '/admissions_/faq',
  path: '/admissions/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsApplyOnlineRoute = AdmissionsApplyOnlineRouteImport.update({
  id: '/admissions_/apply-online',
  path: '/admissions/apply-online',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsApplicationProcessRoute =
  AdmissionsApplicationProcessRouteImport.update({
    id: '/admissions_/application-process',
    path: '/admissions/application-process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutWhyLighthouseRoute = AboutWhyLighthouseRouteImport.update({
  id: '/about_/why-lighthouse',
  path: '/about/why-lighthouse',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVisionRoute = AboutVisionRouteImport.update({
  id: '/about_/vision',
  path: '/about/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurStoryRoute = AboutOurStoryRouteImport.update({
  id: '/about_/our-story',
  path: '/about/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/about_/mission',
  path: '/about/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/about_/leadership',
  path: '/about/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutGovernanceRoute = AboutGovernanceRouteImport.update({
  id: '/about_/governance',
  path: '/about/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutEducationalPhilosophyRoute =
  AboutEducationalPhilosophyRouteImport.update({
    id: '/about_/educational-philosophy',
    path: '/about/educational-philosophy',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutCoreValuesRoute = AboutCoreValuesRouteImport.update({
  id: '/about_/core-values',
  path: '/about/core-values',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCampusCultureRoute = AboutCampusCultureRouteImport.update({
  id: '/about_/campus-culture',
  path: '/about/campus-culture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-experience': typeof AcademicExperienceRoute
  '/accessibility': typeof AccessibilityRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-experience': typeof CampusExperienceRoute
  '/campuses': typeof CampusesRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/learning-journey': typeof LearningJourneyRoute
  '/news': typeof NewsRoute
  '/our-model': typeof OurModelRoute
  '/parents': typeof ParentsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-life': typeof StudentLifeRoute
  '/terms': typeof TermsRoute
  '/about/campus-culture': typeof AboutCampusCultureRoute
  '/about/core-values': typeof AboutCoreValuesRoute
  '/about/educational-philosophy': typeof AboutEducationalPhilosophyRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/vision': typeof AboutVisionRoute
  '/about/why-lighthouse': typeof AboutWhyLighthouseRoute
  '/admissions/application-process': typeof AdmissionsApplicationProcessRoute
  '/admissions/apply-online': typeof AdmissionsApplyOnlineRoute
  '/admissions/faq': typeof AdmissionsFaqRoute
  '/admissions/requirements': typeof AdmissionsRequirementsRoute
  '/admissions/schedule-a-visit': typeof AdmissionsScheduleAVisitRoute
  '/admissions/scholarships': typeof AdmissionsScholarshipsRoute
  '/admissions/tuition-fees': typeof AdmissionsTuitionFeesRoute
  '/campus-experience/assembly-hall': typeof CampusExperienceAssemblyHallRoute
  '/campus-experience/classrooms': typeof CampusExperienceClassroomsRoute
  '/campus-experience/dining': typeof CampusExperienceDiningRoute
  '/campus-experience/health-services': typeof CampusExperienceHealthServicesRoute
  '/campus-experience/innovation-creative-spaces': typeof CampusExperienceInnovationCreativeSpacesRoute
  '/campus-experience/laboratories': typeof CampusExperienceLaboratoriesRoute
  '/campus-experience/library': typeof CampusExperienceLibraryRoute
  '/campus-experience/outdoor-learning': typeof CampusExperienceOutdoorLearningRoute
  '/campus-experience/overview': typeof CampusExperienceOverviewRoute
  '/campus-experience/safety': typeof CampusExperienceSafetyRoute
  '/campus-experience/sports-facilities': typeof CampusExperienceSportsFacilitiesRoute
  '/campus-experience/transportation': typeof CampusExperienceTransportationRoute
  '/campuses/mohandessin': typeof CampusesMohandessinRoute
  '/community/alumni': typeof CommunityAlumniRoute
  '/community/careers': typeof CommunityCareersRoute
  '/community/community-programmes': typeof CommunityCommunityProgrammesRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/partnerships': typeof CommunityPartnershipsRoute
  '/explore/digital-ecosystem': typeof ExploreDigitalEcosystemRoute
  '/learning-journey/early-years': typeof LearningJourneyEarlyYearsRoute
  '/learning-journey/graduation-pathways': typeof LearningJourneyGraduationPathwaysRoute
  '/learning-journey/preparatory': typeof LearningJourneyPreparatoryRoute
  '/learning-journey/primary': typeof LearningJourneyPrimaryRoute
  '/learning-journey/secondary': typeof LearningJourneySecondaryRoute
  '/news/campus-events': typeof NewsCampusEventsRoute
  '/news/community-stories': typeof NewsCommunityStoriesRoute
  '/news/educational-insights': typeof NewsEducationalInsightsRoute
  '/news/parent-guides': typeof NewsParentGuidesRoute
  '/news/research-reflection': typeof NewsResearchReflectionRoute
  '/news/school-news': typeof NewsSchoolNewsRoute
  '/news/student-stories': typeof NewsStudentStoriesRoute
  '/news/teacher-stories': typeof NewsTeacherStoriesRoute
  '/our-model/assessment-framework': typeof OurModelAssessmentFrameworkRoute
  '/our-model/educational-model': typeof OurModelEducationalModelRoute
  '/our-model/graduate-profile': typeof OurModelGraduateProfileRoute
  '/our-model/innovation': typeof OurModelInnovationRoute
  '/our-model/institutional-intelligence': typeof OurModelInstitutionalIntelligenceRoute
  '/our-model/learner-profile': typeof OurModelLearnerProfileRoute
  '/our-model/learning-ecosystem': typeof OurModelLearningEcosystemRoute
  '/our-model/parent-partnership': typeof OurModelParentPartnershipRoute
  '/our-model/student-development': typeof OurModelStudentDevelopmentRoute
  '/our-model/teaching-framework': typeof OurModelTeachingFrameworkRoute
  '/parents/communication': typeof ParentsCommunicationRoute
  '/parents/family-engagement': typeof ParentsFamilyEngagementRoute
  '/parents/family-resources': typeof ParentsFamilyResourcesRoute
  '/parents/parent-journey': typeof ParentsParentJourneyRoute
  '/parents/parent-partnership': typeof ParentsParentPartnershipRoute
  '/parents/parent-portal': typeof ParentsParentPortalRoute
  '/parents/school-calendar': typeof ParentsSchoolCalendarRoute
  '/parents/school-policies': typeof ParentsSchoolPoliciesRoute
  '/student-life/arts-performance': typeof StudentLifeArtsPerformanceRoute
  '/student-life/athletics': typeof StudentLifeAthleticsRoute
  '/student-life/clubs-activities': typeof StudentLifeClubsActivitiesRoute
  '/student-life/community-belonging': typeof StudentLifeCommunityBelongingRoute
  '/student-life/events': typeof StudentLifeEventsRoute
  '/student-life/leadership-service': typeof StudentLifeLeadershipServiceRoute
  '/student-life/wellbeing': typeof StudentLifeWellbeingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-experience': typeof AcademicExperienceRoute
  '/accessibility': typeof AccessibilityRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-experience': typeof CampusExperienceRoute
  '/campuses': typeof CampusesRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/learning-journey': typeof LearningJourneyRoute
  '/news': typeof NewsRoute
  '/our-model': typeof OurModelRoute
  '/parents': typeof ParentsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-life': typeof StudentLifeRoute
  '/terms': typeof TermsRoute
  '/about/campus-culture': typeof AboutCampusCultureRoute
  '/about/core-values': typeof AboutCoreValuesRoute
  '/about/educational-philosophy': typeof AboutEducationalPhilosophyRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/vision': typeof AboutVisionRoute
  '/about/why-lighthouse': typeof AboutWhyLighthouseRoute
  '/admissions/application-process': typeof AdmissionsApplicationProcessRoute
  '/admissions/apply-online': typeof AdmissionsApplyOnlineRoute
  '/admissions/faq': typeof AdmissionsFaqRoute
  '/admissions/requirements': typeof AdmissionsRequirementsRoute
  '/admissions/schedule-a-visit': typeof AdmissionsScheduleAVisitRoute
  '/admissions/scholarships': typeof AdmissionsScholarshipsRoute
  '/admissions/tuition-fees': typeof AdmissionsTuitionFeesRoute
  '/campus-experience/assembly-hall': typeof CampusExperienceAssemblyHallRoute
  '/campus-experience/classrooms': typeof CampusExperienceClassroomsRoute
  '/campus-experience/dining': typeof CampusExperienceDiningRoute
  '/campus-experience/health-services': typeof CampusExperienceHealthServicesRoute
  '/campus-experience/innovation-creative-spaces': typeof CampusExperienceInnovationCreativeSpacesRoute
  '/campus-experience/laboratories': typeof CampusExperienceLaboratoriesRoute
  '/campus-experience/library': typeof CampusExperienceLibraryRoute
  '/campus-experience/outdoor-learning': typeof CampusExperienceOutdoorLearningRoute
  '/campus-experience/overview': typeof CampusExperienceOverviewRoute
  '/campus-experience/safety': typeof CampusExperienceSafetyRoute
  '/campus-experience/sports-facilities': typeof CampusExperienceSportsFacilitiesRoute
  '/campus-experience/transportation': typeof CampusExperienceTransportationRoute
  '/campuses/mohandessin': typeof CampusesMohandessinRoute
  '/community/alumni': typeof CommunityAlumniRoute
  '/community/careers': typeof CommunityCareersRoute
  '/community/community-programmes': typeof CommunityCommunityProgrammesRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/partnerships': typeof CommunityPartnershipsRoute
  '/explore/digital-ecosystem': typeof ExploreDigitalEcosystemRoute
  '/learning-journey/early-years': typeof LearningJourneyEarlyYearsRoute
  '/learning-journey/graduation-pathways': typeof LearningJourneyGraduationPathwaysRoute
  '/learning-journey/preparatory': typeof LearningJourneyPreparatoryRoute
  '/learning-journey/primary': typeof LearningJourneyPrimaryRoute
  '/learning-journey/secondary': typeof LearningJourneySecondaryRoute
  '/news/campus-events': typeof NewsCampusEventsRoute
  '/news/community-stories': typeof NewsCommunityStoriesRoute
  '/news/educational-insights': typeof NewsEducationalInsightsRoute
  '/news/parent-guides': typeof NewsParentGuidesRoute
  '/news/research-reflection': typeof NewsResearchReflectionRoute
  '/news/school-news': typeof NewsSchoolNewsRoute
  '/news/student-stories': typeof NewsStudentStoriesRoute
  '/news/teacher-stories': typeof NewsTeacherStoriesRoute
  '/our-model/assessment-framework': typeof OurModelAssessmentFrameworkRoute
  '/our-model/educational-model': typeof OurModelEducationalModelRoute
  '/our-model/graduate-profile': typeof OurModelGraduateProfileRoute
  '/our-model/innovation': typeof OurModelInnovationRoute
  '/our-model/institutional-intelligence': typeof OurModelInstitutionalIntelligenceRoute
  '/our-model/learner-profile': typeof OurModelLearnerProfileRoute
  '/our-model/learning-ecosystem': typeof OurModelLearningEcosystemRoute
  '/our-model/parent-partnership': typeof OurModelParentPartnershipRoute
  '/our-model/student-development': typeof OurModelStudentDevelopmentRoute
  '/our-model/teaching-framework': typeof OurModelTeachingFrameworkRoute
  '/parents/communication': typeof ParentsCommunicationRoute
  '/parents/family-engagement': typeof ParentsFamilyEngagementRoute
  '/parents/family-resources': typeof ParentsFamilyResourcesRoute
  '/parents/parent-journey': typeof ParentsParentJourneyRoute
  '/parents/parent-partnership': typeof ParentsParentPartnershipRoute
  '/parents/parent-portal': typeof ParentsParentPortalRoute
  '/parents/school-calendar': typeof ParentsSchoolCalendarRoute
  '/parents/school-policies': typeof ParentsSchoolPoliciesRoute
  '/student-life/arts-performance': typeof StudentLifeArtsPerformanceRoute
  '/student-life/athletics': typeof StudentLifeAthleticsRoute
  '/student-life/clubs-activities': typeof StudentLifeClubsActivitiesRoute
  '/student-life/community-belonging': typeof StudentLifeCommunityBelongingRoute
  '/student-life/events': typeof StudentLifeEventsRoute
  '/student-life/leadership-service': typeof StudentLifeLeadershipServiceRoute
  '/student-life/wellbeing': typeof StudentLifeWellbeingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-experience': typeof AcademicExperienceRoute
  '/accessibility': typeof AccessibilityRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-experience': typeof CampusExperienceRoute
  '/campuses': typeof CampusesRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/learning-journey': typeof LearningJourneyRoute
  '/news': typeof NewsRoute
  '/our-model': typeof OurModelRoute
  '/parents': typeof ParentsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-life': typeof StudentLifeRoute
  '/terms': typeof TermsRoute
  '/about_/campus-culture': typeof AboutCampusCultureRoute
  '/about_/core-values': typeof AboutCoreValuesRoute
  '/about_/educational-philosophy': typeof AboutEducationalPhilosophyRoute
  '/about_/governance': typeof AboutGovernanceRoute
  '/about_/leadership': typeof AboutLeadershipRoute
  '/about_/mission': typeof AboutMissionRoute
  '/about_/our-story': typeof AboutOurStoryRoute
  '/about_/vision': typeof AboutVisionRoute
  '/about_/why-lighthouse': typeof AboutWhyLighthouseRoute
  '/admissions_/application-process': typeof AdmissionsApplicationProcessRoute
  '/admissions_/apply-online': typeof AdmissionsApplyOnlineRoute
  '/admissions_/faq': typeof AdmissionsFaqRoute
  '/admissions_/requirements': typeof AdmissionsRequirementsRoute
  '/admissions_/schedule-a-visit': typeof AdmissionsScheduleAVisitRoute
  '/admissions_/scholarships': typeof AdmissionsScholarshipsRoute
  '/admissions_/tuition-fees': typeof AdmissionsTuitionFeesRoute
  '/campus-experience_/assembly-hall': typeof CampusExperienceAssemblyHallRoute
  '/campus-experience_/classrooms': typeof CampusExperienceClassroomsRoute
  '/campus-experience_/dining': typeof CampusExperienceDiningRoute
  '/campus-experience_/health-services': typeof CampusExperienceHealthServicesRoute
  '/campus-experience_/innovation-creative-spaces': typeof CampusExperienceInnovationCreativeSpacesRoute
  '/campus-experience_/laboratories': typeof CampusExperienceLaboratoriesRoute
  '/campus-experience_/library': typeof CampusExperienceLibraryRoute
  '/campus-experience_/outdoor-learning': typeof CampusExperienceOutdoorLearningRoute
  '/campus-experience_/overview': typeof CampusExperienceOverviewRoute
  '/campus-experience_/safety': typeof CampusExperienceSafetyRoute
  '/campus-experience_/sports-facilities': typeof CampusExperienceSportsFacilitiesRoute
  '/campus-experience_/transportation': typeof CampusExperienceTransportationRoute
  '/campuses_/mohandessin': typeof CampusesMohandessinRoute
  '/community_/alumni': typeof CommunityAlumniRoute
  '/community_/careers': typeof CommunityCareersRoute
  '/community_/community-programmes': typeof CommunityCommunityProgrammesRoute
  '/community_/events': typeof CommunityEventsRoute
  '/community_/partnerships': typeof CommunityPartnershipsRoute
  '/explore/digital-ecosystem': typeof ExploreDigitalEcosystemRoute
  '/learning-journey_/early-years': typeof LearningJourneyEarlyYearsRoute
  '/learning-journey_/graduation-pathways': typeof LearningJourneyGraduationPathwaysRoute
  '/learning-journey_/preparatory': typeof LearningJourneyPreparatoryRoute
  '/learning-journey_/primary': typeof LearningJourneyPrimaryRoute
  '/learning-journey_/secondary': typeof LearningJourneySecondaryRoute
  '/news_/campus-events': typeof NewsCampusEventsRoute
  '/news_/community-stories': typeof NewsCommunityStoriesRoute
  '/news_/educational-insights': typeof NewsEducationalInsightsRoute
  '/news_/parent-guides': typeof NewsParentGuidesRoute
  '/news_/research-reflection': typeof NewsResearchReflectionRoute
  '/news_/school-news': typeof NewsSchoolNewsRoute
  '/news_/student-stories': typeof NewsStudentStoriesRoute
  '/news_/teacher-stories': typeof NewsTeacherStoriesRoute
  '/our-model_/assessment-framework': typeof OurModelAssessmentFrameworkRoute
  '/our-model_/educational-model': typeof OurModelEducationalModelRoute
  '/our-model_/graduate-profile': typeof OurModelGraduateProfileRoute
  '/our-model_/innovation': typeof OurModelInnovationRoute
  '/our-model_/institutional-intelligence': typeof OurModelInstitutionalIntelligenceRoute
  '/our-model_/learner-profile': typeof OurModelLearnerProfileRoute
  '/our-model_/learning-ecosystem': typeof OurModelLearningEcosystemRoute
  '/our-model_/parent-partnership': typeof OurModelParentPartnershipRoute
  '/our-model_/student-development': typeof OurModelStudentDevelopmentRoute
  '/our-model_/teaching-framework': typeof OurModelTeachingFrameworkRoute
  '/parents_/communication': typeof ParentsCommunicationRoute
  '/parents_/family-engagement': typeof ParentsFamilyEngagementRoute
  '/parents_/family-resources': typeof ParentsFamilyResourcesRoute
  '/parents_/parent-journey': typeof ParentsParentJourneyRoute
  '/parents_/parent-partnership': typeof ParentsParentPartnershipRoute
  '/parents_/parent-portal': typeof ParentsParentPortalRoute
  '/parents_/school-calendar': typeof ParentsSchoolCalendarRoute
  '/parents_/school-policies': typeof ParentsSchoolPoliciesRoute
  '/student-life_/arts-performance': typeof StudentLifeArtsPerformanceRoute
  '/student-life_/athletics': typeof StudentLifeAthleticsRoute
  '/student-life_/clubs-activities': typeof StudentLifeClubsActivitiesRoute
  '/student-life_/community-belonging': typeof StudentLifeCommunityBelongingRoute
  '/student-life_/events': typeof StudentLifeEventsRoute
  '/student-life_/leadership-service': typeof StudentLifeLeadershipServiceRoute
  '/student-life_/wellbeing': typeof StudentLifeWellbeingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic-experience'
    | '/accessibility'
    | '/admissions'
    | '/campus-experience'
    | '/campuses'
    | '/careers'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/learning-journey'
    | '/news'
    | '/our-model'
    | '/parents'
    | '/privacy'
    | '/sitemap.xml'
    | '/student-life'
    | '/terms'
    | '/about/campus-culture'
    | '/about/core-values'
    | '/about/educational-philosophy'
    | '/about/governance'
    | '/about/leadership'
    | '/about/mission'
    | '/about/our-story'
    | '/about/vision'
    | '/about/why-lighthouse'
    | '/admissions/application-process'
    | '/admissions/apply-online'
    | '/admissions/faq'
    | '/admissions/requirements'
    | '/admissions/schedule-a-visit'
    | '/admissions/scholarships'
    | '/admissions/tuition-fees'
    | '/campus-experience/assembly-hall'
    | '/campus-experience/classrooms'
    | '/campus-experience/dining'
    | '/campus-experience/health-services'
    | '/campus-experience/innovation-creative-spaces'
    | '/campus-experience/laboratories'
    | '/campus-experience/library'
    | '/campus-experience/outdoor-learning'
    | '/campus-experience/overview'
    | '/campus-experience/safety'
    | '/campus-experience/sports-facilities'
    | '/campus-experience/transportation'
    | '/campuses/mohandessin'
    | '/community/alumni'
    | '/community/careers'
    | '/community/community-programmes'
    | '/community/events'
    | '/community/partnerships'
    | '/explore/digital-ecosystem'
    | '/learning-journey/early-years'
    | '/learning-journey/graduation-pathways'
    | '/learning-journey/preparatory'
    | '/learning-journey/primary'
    | '/learning-journey/secondary'
    | '/news/campus-events'
    | '/news/community-stories'
    | '/news/educational-insights'
    | '/news/parent-guides'
    | '/news/research-reflection'
    | '/news/school-news'
    | '/news/student-stories'
    | '/news/teacher-stories'
    | '/our-model/assessment-framework'
    | '/our-model/educational-model'
    | '/our-model/graduate-profile'
    | '/our-model/innovation'
    | '/our-model/institutional-intelligence'
    | '/our-model/learner-profile'
    | '/our-model/learning-ecosystem'
    | '/our-model/parent-partnership'
    | '/our-model/student-development'
    | '/our-model/teaching-framework'
    | '/parents/communication'
    | '/parents/family-engagement'
    | '/parents/family-resources'
    | '/parents/parent-journey'
    | '/parents/parent-partnership'
    | '/parents/parent-portal'
    | '/parents/school-calendar'
    | '/parents/school-policies'
    | '/student-life/arts-performance'
    | '/student-life/athletics'
    | '/student-life/clubs-activities'
    | '/student-life/community-belonging'
    | '/student-life/events'
    | '/student-life/leadership-service'
    | '/student-life/wellbeing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic-experience'
    | '/accessibility'
    | '/admissions'
    | '/campus-experience'
    | '/campuses'
    | '/careers'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/learning-journey'
    | '/news'
    | '/our-model'
    | '/parents'
    | '/privacy'
    | '/sitemap.xml'
    | '/student-life'
    | '/terms'
    | '/about/campus-culture'
    | '/about/core-values'
    | '/about/educational-philosophy'
    | '/about/governance'
    | '/about/leadership'
    | '/about/mission'
    | '/about/our-story'
    | '/about/vision'
    | '/about/why-lighthouse'
    | '/admissions/application-process'
    | '/admissions/apply-online'
    | '/admissions/faq'
    | '/admissions/requirements'
    | '/admissions/schedule-a-visit'
    | '/admissions/scholarships'
    | '/admissions/tuition-fees'
    | '/campus-experience/assembly-hall'
    | '/campus-experience/classrooms'
    | '/campus-experience/dining'
    | '/campus-experience/health-services'
    | '/campus-experience/innovation-creative-spaces'
    | '/campus-experience/laboratories'
    | '/campus-experience/library'
    | '/campus-experience/outdoor-learning'
    | '/campus-experience/overview'
    | '/campus-experience/safety'
    | '/campus-experience/sports-facilities'
    | '/campus-experience/transportation'
    | '/campuses/mohandessin'
    | '/community/alumni'
    | '/community/careers'
    | '/community/community-programmes'
    | '/community/events'
    | '/community/partnerships'
    | '/explore/digital-ecosystem'
    | '/learning-journey/early-years'
    | '/learning-journey/graduation-pathways'
    | '/learning-journey/preparatory'
    | '/learning-journey/primary'
    | '/learning-journey/secondary'
    | '/news/campus-events'
    | '/news/community-stories'
    | '/news/educational-insights'
    | '/news/parent-guides'
    | '/news/research-reflection'
    | '/news/school-news'
    | '/news/student-stories'
    | '/news/teacher-stories'
    | '/our-model/assessment-framework'
    | '/our-model/educational-model'
    | '/our-model/graduate-profile'
    | '/our-model/innovation'
    | '/our-model/institutional-intelligence'
    | '/our-model/learner-profile'
    | '/our-model/learning-ecosystem'
    | '/our-model/parent-partnership'
    | '/our-model/student-development'
    | '/our-model/teaching-framework'
    | '/parents/communication'
    | '/parents/family-engagement'
    | '/parents/family-resources'
    | '/parents/parent-journey'
    | '/parents/parent-partnership'
    | '/parents/parent-portal'
    | '/parents/school-calendar'
    | '/parents/school-policies'
    | '/student-life/arts-performance'
    | '/student-life/athletics'
    | '/student-life/clubs-activities'
    | '/student-life/community-belonging'
    | '/student-life/events'
    | '/student-life/leadership-service'
    | '/student-life/wellbeing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic-experience'
    | '/accessibility'
    | '/admissions'
    | '/campus-experience'
    | '/campuses'
    | '/careers'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/learning-journey'
    | '/news'
    | '/our-model'
    | '/parents'
    | '/privacy'
    | '/sitemap.xml'
    | '/student-life'
    | '/terms'
    | '/about_/campus-culture'
    | '/about_/core-values'
    | '/about_/educational-philosophy'
    | '/about_/governance'
    | '/about_/leadership'
    | '/about_/mission'
    | '/about_/our-story'
    | '/about_/vision'
    | '/about_/why-lighthouse'
    | '/admissions_/application-process'
    | '/admissions_/apply-online'
    | '/admissions_/faq'
    | '/admissions_/requirements'
    | '/admissions_/schedule-a-visit'
    | '/admissions_/scholarships'
    | '/admissions_/tuition-fees'
    | '/campus-experience_/assembly-hall'
    | '/campus-experience_/classrooms'
    | '/campus-experience_/dining'
    | '/campus-experience_/health-services'
    | '/campus-experience_/innovation-creative-spaces'
    | '/campus-experience_/laboratories'
    | '/campus-experience_/library'
    | '/campus-experience_/outdoor-learning'
    | '/campus-experience_/overview'
    | '/campus-experience_/safety'
    | '/campus-experience_/sports-facilities'
    | '/campus-experience_/transportation'
    | '/campuses_/mohandessin'
    | '/community_/alumni'
    | '/community_/careers'
    | '/community_/community-programmes'
    | '/community_/events'
    | '/community_/partnerships'
    | '/explore/digital-ecosystem'
    | '/learning-journey_/early-years'
    | '/learning-journey_/graduation-pathways'
    | '/learning-journey_/preparatory'
    | '/learning-journey_/primary'
    | '/learning-journey_/secondary'
    | '/news_/campus-events'
    | '/news_/community-stories'
    | '/news_/educational-insights'
    | '/news_/parent-guides'
    | '/news_/research-reflection'
    | '/news_/school-news'
    | '/news_/student-stories'
    | '/news_/teacher-stories'
    | '/our-model_/assessment-framework'
    | '/our-model_/educational-model'
    | '/our-model_/graduate-profile'
    | '/our-model_/innovation'
    | '/our-model_/institutional-intelligence'
    | '/our-model_/learner-profile'
    | '/our-model_/learning-ecosystem'
    | '/our-model_/parent-partnership'
    | '/our-model_/student-development'
    | '/our-model_/teaching-framework'
    | '/parents_/communication'
    | '/parents_/family-engagement'
    | '/parents_/family-resources'
    | '/parents_/parent-journey'
    | '/parents_/parent-partnership'
    | '/parents_/parent-portal'
    | '/parents_/school-calendar'
    | '/parents_/school-policies'
    | '/student-life_/arts-performance'
    | '/student-life_/athletics'
    | '/student-life_/clubs-activities'
    | '/student-life_/community-belonging'
    | '/student-life_/events'
    | '/student-life_/leadership-service'
    | '/student-life_/wellbeing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicExperienceRoute: typeof AcademicExperienceRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CampusExperienceRoute: typeof CampusExperienceRoute
  CampusesRoute: typeof CampusesRoute
  CareersRoute: typeof CareersRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  LearningJourneyRoute: typeof LearningJourneyRoute
  NewsRoute: typeof NewsRoute
  OurModelRoute: typeof OurModelRoute
  ParentsRoute: typeof ParentsRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentLifeRoute: typeof StudentLifeRoute
  TermsRoute: typeof TermsRoute
  AboutCampusCultureRoute: typeof AboutCampusCultureRoute
  AboutCoreValuesRoute: typeof AboutCoreValuesRoute
  AboutEducationalPhilosophyRoute: typeof AboutEducationalPhilosophyRoute
  AboutGovernanceRoute: typeof AboutGovernanceRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutMissionRoute: typeof AboutMissionRoute
  AboutOurStoryRoute: typeof AboutOurStoryRoute
  AboutVisionRoute: typeof AboutVisionRoute
  AboutWhyLighthouseRoute: typeof AboutWhyLighthouseRoute
  AdmissionsApplicationProcessRoute: typeof AdmissionsApplicationProcessRoute
  AdmissionsApplyOnlineRoute: typeof AdmissionsApplyOnlineRoute
  AdmissionsFaqRoute: typeof AdmissionsFaqRoute
  AdmissionsRequirementsRoute: typeof AdmissionsRequirementsRoute
  AdmissionsScheduleAVisitRoute: typeof AdmissionsScheduleAVisitRoute
  AdmissionsScholarshipsRoute: typeof AdmissionsScholarshipsRoute
  AdmissionsTuitionFeesRoute: typeof AdmissionsTuitionFeesRoute
  CampusExperienceAssemblyHallRoute: typeof CampusExperienceAssemblyHallRoute
  CampusExperienceClassroomsRoute: typeof CampusExperienceClassroomsRoute
  CampusExperienceDiningRoute: typeof CampusExperienceDiningRoute
  CampusExperienceHealthServicesRoute: typeof CampusExperienceHealthServicesRoute
  CampusExperienceInnovationCreativeSpacesRoute: typeof CampusExperienceInnovationCreativeSpacesRoute
  CampusExperienceLaboratoriesRoute: typeof CampusExperienceLaboratoriesRoute
  CampusExperienceLibraryRoute: typeof CampusExperienceLibraryRoute
  CampusExperienceOutdoorLearningRoute: typeof CampusExperienceOutdoorLearningRoute
  CampusExperienceOverviewRoute: typeof CampusExperienceOverviewRoute
  CampusExperienceSafetyRoute: typeof CampusExperienceSafetyRoute
  CampusExperienceSportsFacilitiesRoute: typeof CampusExperienceSportsFacilitiesRoute
  CampusExperienceTransportationRoute: typeof CampusExperienceTransportationRoute
  CampusesMohandessinRoute: typeof CampusesMohandessinRoute
  CommunityAlumniRoute: typeof CommunityAlumniRoute
  CommunityCareersRoute: typeof CommunityCareersRoute
  CommunityCommunityProgrammesRoute: typeof CommunityCommunityProgrammesRoute
  CommunityEventsRoute: typeof CommunityEventsRoute
  CommunityPartnershipsRoute: typeof CommunityPartnershipsRoute
  ExploreDigitalEcosystemRoute: typeof ExploreDigitalEcosystemRoute
  LearningJourneyEarlyYearsRoute: typeof LearningJourneyEarlyYearsRoute
  LearningJourneyGraduationPathwaysRoute: typeof LearningJourneyGraduationPathwaysRoute
  LearningJourneyPreparatoryRoute: typeof LearningJourneyPreparatoryRoute
  LearningJourneyPrimaryRoute: typeof LearningJourneyPrimaryRoute
  LearningJourneySecondaryRoute: typeof LearningJourneySecondaryRoute
  NewsCampusEventsRoute: typeof NewsCampusEventsRoute
  NewsCommunityStoriesRoute: typeof NewsCommunityStoriesRoute
  NewsEducationalInsightsRoute: typeof NewsEducationalInsightsRoute
  NewsParentGuidesRoute: typeof NewsParentGuidesRoute
  NewsResearchReflectionRoute: typeof NewsResearchReflectionRoute
  NewsSchoolNewsRoute: typeof NewsSchoolNewsRoute
  NewsStudentStoriesRoute: typeof NewsStudentStoriesRoute
  NewsTeacherStoriesRoute: typeof NewsTeacherStoriesRoute
  OurModelAssessmentFrameworkRoute: typeof OurModelAssessmentFrameworkRoute
  OurModelEducationalModelRoute: typeof OurModelEducationalModelRoute
  OurModelGraduateProfileRoute: typeof OurModelGraduateProfileRoute
  OurModelInnovationRoute: typeof OurModelInnovationRoute
  OurModelInstitutionalIntelligenceRoute: typeof OurModelInstitutionalIntelligenceRoute
  OurModelLearnerProfileRoute: typeof OurModelLearnerProfileRoute
  OurModelLearningEcosystemRoute: typeof OurModelLearningEcosystemRoute
  OurModelParentPartnershipRoute: typeof OurModelParentPartnershipRoute
  OurModelStudentDevelopmentRoute: typeof OurModelStudentDevelopmentRoute
  OurModelTeachingFrameworkRoute: typeof OurModelTeachingFrameworkRoute
  ParentsCommunicationRoute: typeof ParentsCommunicationRoute
  ParentsFamilyEngagementRoute: typeof ParentsFamilyEngagementRoute
  ParentsFamilyResourcesRoute: typeof ParentsFamilyResourcesRoute
  ParentsParentJourneyRoute: typeof ParentsParentJourneyRoute
  ParentsParentPartnershipRoute: typeof ParentsParentPartnershipRoute
  ParentsParentPortalRoute: typeof ParentsParentPortalRoute
  ParentsSchoolCalendarRoute: typeof ParentsSchoolCalendarRoute
  ParentsSchoolPoliciesRoute: typeof ParentsSchoolPoliciesRoute
  StudentLifeArtsPerformanceRoute: typeof StudentLifeArtsPerformanceRoute
  StudentLifeAthleticsRoute: typeof StudentLifeAthleticsRoute
  StudentLifeClubsActivitiesRoute: typeof StudentLifeClubsActivitiesRoute
  StudentLifeCommunityBelongingRoute: typeof StudentLifeCommunityBelongingRoute
  StudentLifeEventsRoute: typeof StudentLifeEventsRoute
  StudentLifeLeadershipServiceRoute: typeof StudentLifeLeadershipServiceRoute
  StudentLifeWellbeingRoute: typeof StudentLifeWellbeingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life': {
      id: '/student-life'
      path: '/student-life'
      fullPath: '/student-life'
      preLoaderRoute: typeof StudentLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-model': {
      id: '/our-model'
      path: '/our-model'
      fullPath: '/our-model'
      preLoaderRoute: typeof OurModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-journey': {
      id: '/learning-journey'
      path: '/learning-journey'
      fullPath: '/learning-journey'
      preLoaderRoute: typeof LearningJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses': {
      id: '/campuses'
      path: '/campuses'
      fullPath: '/campuses'
      preLoaderRoute: typeof CampusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience': {
      id: '/campus-experience'
      path: '/campus-experience'
      fullPath: '/campus-experience'
      preLoaderRoute: typeof CampusExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-experience': {
      id: '/academic-experience'
      path: '/academic-experience'
      fullPath: '/academic-experience'
      preLoaderRoute: typeof AcademicExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life_/wellbeing': {
      id: '/student-life_/wellbeing'
      path: '/student-life/wellbeing'
      fullPath: '/student-life/wellbeing'
      preLoaderRoute: typeof StudentLifeWellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life_/leadership-service': {
      id: '/student-life_/leadership-service'
      path: '/student-life/leadership-service'
      fullPath: '/student-life/leadership-service'
      preLoaderRoute: typeof StudentLifeLeadershipServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life_/events': {
      id: '/student-life_/events'
      path: '/student-life/events'
      fullPath: '/student-life/events'
      preLoaderRoute: typeof StudentLifeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life_/community-belonging': {
      id: '/student-life_/community-belonging'
      path: '/student-life/community-belonging'
      fullPath: '/student-life/community-belonging'
      preLoaderRoute: typeof StudentLifeCommunityBelongingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life_/clubs-activities': {
      id: '/student-life_/clubs-activities'
      path: '/student-life/clubs-activities'
      fullPath: '/student-life/clubs-activities'
      preLoaderRoute: typeof StudentLifeClubsActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life_/athletics': {
      id: '/student-life_/athletics'
      path: '/student-life/athletics'
      fullPath: '/student-life/athletics'
      preLoaderRoute: typeof StudentLifeAthleticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life_/arts-performance': {
      id: '/student-life_/arts-performance'
      path: '/student-life/arts-performance'
      fullPath: '/student-life/arts-performance'
      preLoaderRoute: typeof StudentLifeArtsPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents_/school-policies': {
      id: '/parents_/school-policies'
      path: '/parents/school-policies'
      fullPath: '/parents/school-policies'
      preLoaderRoute: typeof ParentsSchoolPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents_/school-calendar': {
      id: '/parents_/school-calendar'
      path: '/parents/school-calendar'
      fullPath: '/parents/school-calendar'
      preLoaderRoute: typeof ParentsSchoolCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents_/parent-portal': {
      id: '/parents_/parent-portal'
      path: '/parents/parent-portal'
      fullPath: '/parents/parent-portal'
      preLoaderRoute: typeof ParentsParentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents_/parent-partnership': {
      id: '/parents_/parent-partnership'
      path: '/parents/parent-partnership'
      fullPath: '/parents/parent-partnership'
      preLoaderRoute: typeof ParentsParentPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents_/parent-journey': {
      id: '/parents_/parent-journey'
      path: '/parents/parent-journey'
      fullPath: '/parents/parent-journey'
      preLoaderRoute: typeof ParentsParentJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents_/family-resources': {
      id: '/parents_/family-resources'
      path: '/parents/family-resources'
      fullPath: '/parents/family-resources'
      preLoaderRoute: typeof ParentsFamilyResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents_/family-engagement': {
      id: '/parents_/family-engagement'
      path: '/parents/family-engagement'
      fullPath: '/parents/family-engagement'
      preLoaderRoute: typeof ParentsFamilyEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents_/communication': {
      id: '/parents_/communication'
      path: '/parents/communication'
      fullPath: '/parents/communication'
      preLoaderRoute: typeof ParentsCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-model_/teaching-framework': {
      id: '/our-model_/teaching-framework'
      path: '/our-model/teaching-framework'
      fullPath: '/our-model/teaching-framework'
      preLoaderRoute: typeof OurModelTeachingFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-model_/student-development': {
      id: '/our-model_/student-development'
      path: '/our-model/student-development'
      fullPath: '/our-model/student-development'
      preLoaderRoute: typeof OurModelStudentDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-model_/parent-partnership': {
      id: '/our-model_/parent-partnership'
      path: '/our-model/parent-partnership'
      fullPath: '/our-model/parent-partnership'
      preLoaderRoute: typeof OurModelParentPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-model_/learning-ecosystem': {
      id: '/our-model_/learning-ecosystem'
      path: '/our-model/learning-ecosystem'
      fullPath: '/our-model/learning-ecosystem'
      preLoaderRoute: typeof OurModelLearningEcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-model_/learner-profile': {
      id: '/our-model_/learner-profile'
      path: '/our-model/learner-profile'
      fullPath: '/our-model/learner-profile'
      preLoaderRoute: typeof OurModelLearnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-model_/institutional-intelligence': {
      id: '/our-model_/institutional-intelligence'
      path: '/our-model/institutional-intelligence'
      fullPath: '/our-model/institutional-intelligence'
      preLoaderRoute: typeof OurModelInstitutionalIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-model_/innovation': {
      id: '/our-model_/innovation'
      path: '/our-model/innovation'
      fullPath: '/our-model/innovation'
      preLoaderRoute: typeof OurModelInnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-model_/graduate-profile': {
      id: '/our-model_/graduate-profile'
      path: '/our-model/graduate-profile'
      fullPath: '/our-model/graduate-profile'
      preLoaderRoute: typeof OurModelGraduateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-model_/educational-model': {
      id: '/our-model_/educational-model'
      path: '/our-model/educational-model'
      fullPath: '/our-model/educational-model'
      preLoaderRoute: typeof OurModelEducationalModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-model_/assessment-framework': {
      id: '/our-model_/assessment-framework'
      path: '/our-model/assessment-framework'
      fullPath: '/our-model/assessment-framework'
      preLoaderRoute: typeof OurModelAssessmentFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/teacher-stories': {
      id: '/news_/teacher-stories'
      path: '/news/teacher-stories'
      fullPath: '/news/teacher-stories'
      preLoaderRoute: typeof NewsTeacherStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/student-stories': {
      id: '/news_/student-stories'
      path: '/news/student-stories'
      fullPath: '/news/student-stories'
      preLoaderRoute: typeof NewsStudentStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/school-news': {
      id: '/news_/school-news'
      path: '/news/school-news'
      fullPath: '/news/school-news'
      preLoaderRoute: typeof NewsSchoolNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/research-reflection': {
      id: '/news_/research-reflection'
      path: '/news/research-reflection'
      fullPath: '/news/research-reflection'
      preLoaderRoute: typeof NewsResearchReflectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/parent-guides': {
      id: '/news_/parent-guides'
      path: '/news/parent-guides'
      fullPath: '/news/parent-guides'
      preLoaderRoute: typeof NewsParentGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/educational-insights': {
      id: '/news_/educational-insights'
      path: '/news/educational-insights'
      fullPath: '/news/educational-insights'
      preLoaderRoute: typeof NewsEducationalInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/community-stories': {
      id: '/news_/community-stories'
      path: '/news/community-stories'
      fullPath: '/news/community-stories'
      preLoaderRoute: typeof NewsCommunityStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/campus-events': {
      id: '/news_/campus-events'
      path: '/news/campus-events'
      fullPath: '/news/campus-events'
      preLoaderRoute: typeof NewsCampusEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-journey_/secondary': {
      id: '/learning-journey_/secondary'
      path: '/learning-journey/secondary'
      fullPath: '/learning-journey/secondary'
      preLoaderRoute: typeof LearningJourneySecondaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-journey_/primary': {
      id: '/learning-journey_/primary'
      path: '/learning-journey/primary'
      fullPath: '/learning-journey/primary'
      preLoaderRoute: typeof LearningJourneyPrimaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-journey_/preparatory': {
      id: '/learning-journey_/preparatory'
      path: '/learning-journey/preparatory'
      fullPath: '/learning-journey/preparatory'
      preLoaderRoute: typeof LearningJourneyPreparatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-journey_/graduation-pathways': {
      id: '/learning-journey_/graduation-pathways'
      path: '/learning-journey/graduation-pathways'
      fullPath: '/learning-journey/graduation-pathways'
      preLoaderRoute: typeof LearningJourneyGraduationPathwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-journey_/early-years': {
      id: '/learning-journey_/early-years'
      path: '/learning-journey/early-years'
      fullPath: '/learning-journey/early-years'
      preLoaderRoute: typeof LearningJourneyEarlyYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/digital-ecosystem': {
      id: '/explore/digital-ecosystem'
      path: '/explore/digital-ecosystem'
      fullPath: '/explore/digital-ecosystem'
      preLoaderRoute: typeof ExploreDigitalEcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/partnerships': {
      id: '/community_/partnerships'
      path: '/community/partnerships'
      fullPath: '/community/partnerships'
      preLoaderRoute: typeof CommunityPartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/events': {
      id: '/community_/events'
      path: '/community/events'
      fullPath: '/community/events'
      preLoaderRoute: typeof CommunityEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/community-programmes': {
      id: '/community_/community-programmes'
      path: '/community/community-programmes'
      fullPath: '/community/community-programmes'
      preLoaderRoute: typeof CommunityCommunityProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/careers': {
      id: '/community_/careers'
      path: '/community/careers'
      fullPath: '/community/careers'
      preLoaderRoute: typeof CommunityCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/alumni': {
      id: '/community_/alumni'
      path: '/community/alumni'
      fullPath: '/community/alumni'
      preLoaderRoute: typeof CommunityAlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses_/mohandessin': {
      id: '/campuses_/mohandessin'
      path: '/campuses/mohandessin'
      fullPath: '/campuses/mohandessin'
      preLoaderRoute: typeof CampusesMohandessinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/transportation': {
      id: '/campus-experience_/transportation'
      path: '/campus-experience/transportation'
      fullPath: '/campus-experience/transportation'
      preLoaderRoute: typeof CampusExperienceTransportationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/sports-facilities': {
      id: '/campus-experience_/sports-facilities'
      path: '/campus-experience/sports-facilities'
      fullPath: '/campus-experience/sports-facilities'
      preLoaderRoute: typeof CampusExperienceSportsFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/safety': {
      id: '/campus-experience_/safety'
      path: '/campus-experience/safety'
      fullPath: '/campus-experience/safety'
      preLoaderRoute: typeof CampusExperienceSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/overview': {
      id: '/campus-experience_/overview'
      path: '/campus-experience/overview'
      fullPath: '/campus-experience/overview'
      preLoaderRoute: typeof CampusExperienceOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/outdoor-learning': {
      id: '/campus-experience_/outdoor-learning'
      path: '/campus-experience/outdoor-learning'
      fullPath: '/campus-experience/outdoor-learning'
      preLoaderRoute: typeof CampusExperienceOutdoorLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/library': {
      id: '/campus-experience_/library'
      path: '/campus-experience/library'
      fullPath: '/campus-experience/library'
      preLoaderRoute: typeof CampusExperienceLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/laboratories': {
      id: '/campus-experience_/laboratories'
      path: '/campus-experience/laboratories'
      fullPath: '/campus-experience/laboratories'
      preLoaderRoute: typeof CampusExperienceLaboratoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/innovation-creative-spaces': {
      id: '/campus-experience_/innovation-creative-spaces'
      path: '/campus-experience/innovation-creative-spaces'
      fullPath: '/campus-experience/innovation-creative-spaces'
      preLoaderRoute: typeof CampusExperienceInnovationCreativeSpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/health-services': {
      id: '/campus-experience_/health-services'
      path: '/campus-experience/health-services'
      fullPath: '/campus-experience/health-services'
      preLoaderRoute: typeof CampusExperienceHealthServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/dining': {
      id: '/campus-experience_/dining'
      path: '/campus-experience/dining'
      fullPath: '/campus-experience/dining'
      preLoaderRoute: typeof CampusExperienceDiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/classrooms': {
      id: '/campus-experience_/classrooms'
      path: '/campus-experience/classrooms'
      fullPath: '/campus-experience/classrooms'
      preLoaderRoute: typeof CampusExperienceClassroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience_/assembly-hall': {
      id: '/campus-experience_/assembly-hall'
      path: '/campus-experience/assembly-hall'
      fullPath: '/campus-experience/assembly-hall'
      preLoaderRoute: typeof CampusExperienceAssemblyHallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions_/tuition-fees': {
      id: '/admissions_/tuition-fees'
      path: '/admissions/tuition-fees'
      fullPath: '/admissions/tuition-fees'
      preLoaderRoute: typeof AdmissionsTuitionFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions_/scholarships': {
      id: '/admissions_/scholarships'
      path: '/admissions/scholarships'
      fullPath: '/admissions/scholarships'
      preLoaderRoute: typeof AdmissionsScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions_/schedule-a-visit': {
      id: '/admissions_/schedule-a-visit'
      path: '/admissions/schedule-a-visit'
      fullPath: '/admissions/schedule-a-visit'
      preLoaderRoute: typeof AdmissionsScheduleAVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions_/requirements': {
      id: '/admissions_/requirements'
      path: '/admissions/requirements'
      fullPath: '/admissions/requirements'
      preLoaderRoute: typeof AdmissionsRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions_/faq': {
      id: '/admissions_/faq'
      path: '/admissions/faq'
      fullPath: '/admissions/faq'
      preLoaderRoute: typeof AdmissionsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions_/apply-online': {
      id: '/admissions_/apply-online'
      path: '/admissions/apply-online'
      fullPath: '/admissions/apply-online'
      preLoaderRoute: typeof AdmissionsApplyOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions_/application-process': {
      id: '/admissions_/application-process'
      path: '/admissions/application-process'
      fullPath: '/admissions/application-process'
      preLoaderRoute: typeof AdmissionsApplicationProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/why-lighthouse': {
      id: '/about_/why-lighthouse'
      path: '/about/why-lighthouse'
      fullPath: '/about/why-lighthouse'
      preLoaderRoute: typeof AboutWhyLighthouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/vision': {
      id: '/about_/vision'
      path: '/about/vision'
      fullPath: '/about/vision'
      preLoaderRoute: typeof AboutVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/our-story': {
      id: '/about_/our-story'
      path: '/about/our-story'
      fullPath: '/about/our-story'
      preLoaderRoute: typeof AboutOurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/mission': {
      id: '/about_/mission'
      path: '/about/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/leadership': {
      id: '/about_/leadership'
      path: '/about/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/governance': {
      id: '/about_/governance'
      path: '/about/governance'
      fullPath: '/about/governance'
      preLoaderRoute: typeof AboutGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/educational-philosophy': {
      id: '/about_/educational-philosophy'
      path: '/about/educational-philosophy'
      fullPath: '/about/educational-philosophy'
      preLoaderRoute: typeof AboutEducationalPhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/core-values': {
      id: '/about_/core-values'
      path: '/about/core-values'
      fullPath: '/about/core-values'
      preLoaderRoute: typeof AboutCoreValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/campus-culture': {
      id: '/about_/campus-culture'
      path: '/about/campus-culture'
      fullPath: '/about/campus-culture'
      preLoaderRoute: typeof AboutCampusCultureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicExperienceRoute: AcademicExperienceRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdmissionsRoute: AdmissionsRoute,
  CampusExperienceRoute: CampusExperienceRoute,
  CampusesRoute: CampusesRoute,
  CareersRoute: CareersRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  LearningJourneyRoute: LearningJourneyRoute,
  NewsRoute: NewsRoute,
  OurModelRoute: OurModelRoute,
  ParentsRoute: ParentsRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentLifeRoute: StudentLifeRoute,
  TermsRoute: TermsRoute,
  AboutCampusCultureRoute: AboutCampusCultureRoute,
  AboutCoreValuesRoute: AboutCoreValuesRoute,
  AboutEducationalPhilosophyRoute: AboutEducationalPhilosophyRoute,
  AboutGovernanceRoute: AboutGovernanceRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutMissionRoute: AboutMissionRoute,
  AboutOurStoryRoute: AboutOurStoryRoute,
  AboutVisionRoute: AboutVisionRoute,
  AboutWhyLighthouseRoute: AboutWhyLighthouseRoute,
  AdmissionsApplicationProcessRoute: AdmissionsApplicationProcessRoute,
  AdmissionsApplyOnlineRoute: AdmissionsApplyOnlineRoute,
  AdmissionsFaqRoute: AdmissionsFaqRoute,
  AdmissionsRequirementsRoute: AdmissionsRequirementsRoute,
  AdmissionsScheduleAVisitRoute: AdmissionsScheduleAVisitRoute,
  AdmissionsScholarshipsRoute: AdmissionsScholarshipsRoute,
  AdmissionsTuitionFeesRoute: AdmissionsTuitionFeesRoute,
  CampusExperienceAssemblyHallRoute: CampusExperienceAssemblyHallRoute,
  CampusExperienceClassroomsRoute: CampusExperienceClassroomsRoute,
  CampusExperienceDiningRoute: CampusExperienceDiningRoute,
  CampusExperienceHealthServicesRoute: CampusExperienceHealthServicesRoute,
  CampusExperienceInnovationCreativeSpacesRoute:
    CampusExperienceInnovationCreativeSpacesRoute,
  CampusExperienceLaboratoriesRoute: CampusExperienceLaboratoriesRoute,
  CampusExperienceLibraryRoute: CampusExperienceLibraryRoute,
  CampusExperienceOutdoorLearningRoute: CampusExperienceOutdoorLearningRoute,
  CampusExperienceOverviewRoute: CampusExperienceOverviewRoute,
  CampusExperienceSafetyRoute: CampusExperienceSafetyRoute,
  CampusExperienceSportsFacilitiesRoute: CampusExperienceSportsFacilitiesRoute,
  CampusExperienceTransportationRoute: CampusExperienceTransportationRoute,
  CampusesMohandessinRoute: CampusesMohandessinRoute,
  CommunityAlumniRoute: CommunityAlumniRoute,
  CommunityCareersRoute: CommunityCareersRoute,
  CommunityCommunityProgrammesRoute: CommunityCommunityProgrammesRoute,
  CommunityEventsRoute: CommunityEventsRoute,
  CommunityPartnershipsRoute: CommunityPartnershipsRoute,
  ExploreDigitalEcosystemRoute: ExploreDigitalEcosystemRoute,
  LearningJourneyEarlyYearsRoute: LearningJourneyEarlyYearsRoute,
  LearningJourneyGraduationPathwaysRoute:
    LearningJourneyGraduationPathwaysRoute,
  LearningJourneyPreparatoryRoute: LearningJourneyPreparatoryRoute,
  LearningJourneyPrimaryRoute: LearningJourneyPrimaryRoute,
  LearningJourneySecondaryRoute: LearningJourneySecondaryRoute,
  NewsCampusEventsRoute: NewsCampusEventsRoute,
  NewsCommunityStoriesRoute: NewsCommunityStoriesRoute,
  NewsEducationalInsightsRoute: NewsEducationalInsightsRoute,
  NewsParentGuidesRoute: NewsParentGuidesRoute,
  NewsResearchReflectionRoute: NewsResearchReflectionRoute,
  NewsSchoolNewsRoute: NewsSchoolNewsRoute,
  NewsStudentStoriesRoute: NewsStudentStoriesRoute,
  NewsTeacherStoriesRoute: NewsTeacherStoriesRoute,
  OurModelAssessmentFrameworkRoute: OurModelAssessmentFrameworkRoute,
  OurModelEducationalModelRoute: OurModelEducationalModelRoute,
  OurModelGraduateProfileRoute: OurModelGraduateProfileRoute,
  OurModelInnovationRoute: OurModelInnovationRoute,
  OurModelInstitutionalIntelligenceRoute:
    OurModelInstitutionalIntelligenceRoute,
  OurModelLearnerProfileRoute: OurModelLearnerProfileRoute,
  OurModelLearningEcosystemRoute: OurModelLearningEcosystemRoute,
  OurModelParentPartnershipRoute: OurModelParentPartnershipRoute,
  OurModelStudentDevelopmentRoute: OurModelStudentDevelopmentRoute,
  OurModelTeachingFrameworkRoute: OurModelTeachingFrameworkRoute,
  ParentsCommunicationRoute: ParentsCommunicationRoute,
  ParentsFamilyEngagementRoute: ParentsFamilyEngagementRoute,
  ParentsFamilyResourcesRoute: ParentsFamilyResourcesRoute,
  ParentsParentJourneyRoute: ParentsParentJourneyRoute,
  ParentsParentPartnershipRoute: ParentsParentPartnershipRoute,
  ParentsParentPortalRoute: ParentsParentPortalRoute,
  ParentsSchoolCalendarRoute: ParentsSchoolCalendarRoute,
  ParentsSchoolPoliciesRoute: ParentsSchoolPoliciesRoute,
  StudentLifeArtsPerformanceRoute: StudentLifeArtsPerformanceRoute,
  StudentLifeAthleticsRoute: StudentLifeAthleticsRoute,
  StudentLifeClubsActivitiesRoute: StudentLifeClubsActivitiesRoute,
  StudentLifeCommunityBelongingRoute: StudentLifeCommunityBelongingRoute,
  StudentLifeEventsRoute: StudentLifeEventsRoute,
  StudentLifeLeadershipServiceRoute: StudentLifeLeadershipServiceRoute,
  StudentLifeWellbeingRoute: StudentLifeWellbeingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
