/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentLifeRouteImport } from './routes/student-life'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as LearningJourneyRouteImport } from './routes/learning-journey'
import { Route as CampusExperienceRouteImport } from './routes/campus-experience'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcademicExperienceRouteImport } from './routes/academic-experience'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StudentLifeRoute = StudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningJourneyRoute = LearningJourneyRouteImport.update({
  id: '/learning-journey',
  path: '/learning-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusExperienceRoute = CampusExperienceRouteImport.update({
  id: '/campus-experience',
  path: '/campus-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicExperienceRoute = AcademicExperienceRouteImport.update({
  id: '/academic-experience',
  path: '/academic-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-experience': typeof AcademicExperienceRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-experience': typeof CampusExperienceRoute
  '/learning-journey': typeof LearningJourneyRoute
  '/parents': typeof ParentsRoute
  '/student-life': typeof StudentLifeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-experience': typeof AcademicExperienceRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-experience': typeof CampusExperienceRoute
  '/learning-journey': typeof LearningJourneyRoute
  '/parents': typeof ParentsRoute
  '/student-life': typeof StudentLifeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-experience': typeof AcademicExperienceRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-experience': typeof CampusExperienceRoute
  '/learning-journey': typeof LearningJourneyRoute
  '/parents': typeof ParentsRoute
  '/student-life': typeof StudentLifeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic-experience'
    | '/admissions'
    | '/campus-experience'
    | '/learning-journey'
    | '/parents'
    | '/student-life'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic-experience'
    | '/admissions'
    | '/campus-experience'
    | '/learning-journey'
    | '/parents'
    | '/student-life'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic-experience'
    | '/admissions'
    | '/campus-experience'
    | '/learning-journey'
    | '/parents'
    | '/student-life'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicExperienceRoute: typeof AcademicExperienceRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CampusExperienceRoute: typeof CampusExperienceRoute
  LearningJourneyRoute: typeof LearningJourneyRoute
  ParentsRoute: typeof ParentsRoute
  StudentLifeRoute: typeof StudentLifeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-life': {
      id: '/student-life'
      path: '/student-life'
      fullPath: '/student-life'
      preLoaderRoute: typeof StudentLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-journey': {
      id: '/learning-journey'
      path: '/learning-journey'
      fullPath: '/learning-journey'
      preLoaderRoute: typeof LearningJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-experience': {
      id: '/campus-experience'
      path: '/campus-experience'
      fullPath: '/campus-experience'
      preLoaderRoute: typeof CampusExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-experience': {
      id: '/academic-experience'
      path: '/academic-experience'
      fullPath: '/academic-experience'
      preLoaderRoute: typeof AcademicExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicExperienceRoute: AcademicExperienceRoute,
  AdmissionsRoute: AdmissionsRoute,
  CampusExperienceRoute: CampusExperienceRoute,
  LearningJourneyRoute: LearningJourneyRoute,
  ParentsRoute: ParentsRoute,
  StudentLifeRoute: StudentLifeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
