// AUTO-GENERATED by scripts/audit-redirects.mjs — do not edit by hand.
export type RedirectRecord = {
  from: string;
  to: string;
  statusCode: number;
  reason: string;
  file: string;
  inboundLinks: { file: string; line: number }[];
};

export const redirectsGeneratedAt = "2026-07-28T17:01:19.066Z";

export const redirectRecords: RedirectRecord[] = [
  {
    "from": "/community/careers",
    "to": "/careers",
    "statusCode": 301,
    "reason": "Interim duplicate of the main Careers page. Permanently consolidated into /careers.",
    "file": "src/routes/community_.careers.tsx",
    "inboundLinks": []
  },
  {
    "from": "/parents/parent-partnership",
    "to": "/our-model/parent-partnership",
    "statusCode": 301,
    "reason": "Duplicate of /our-model/parent-partnership. Consolidated so Parent Partnership exists in exactly one place.",
    "file": "src/routes/parents_.parent-partnership.tsx",
    "inboundLinks": []
  }
];

export const redirectIssues: string[] = [];
